import type { ModelDescriptor } from '@bellasos/contracts';

/**
 * Default model catalog. Cost figures are indicative USD per 1M tokens and are
 * used by the routing engine; they can be overridden at runtime via the model
 * registry / LLM module. Local (Ollama) models are marked privacy-safe.
 */
export const DEFAULT_MODELS: ModelDescriptor[] = [
  {
    id: 'gpt-4o',
    provider: 'openai',
    displayName: 'GPT-4o',
    capabilities: ['chat', 'reasoning', 'tool_use', 'vision'],
    contextWindow: 128000,
    cost: { inputPerMTokensUsd: 2.5, outputPerMTokensUsd: 10 },
    latencyHint: 2,
    local: false,
    enabled: true,
  },
  {
    id: 'gpt-5',
    provider: 'openai',
    displayName: 'GPT-5',
    capabilities: ['chat', 'reasoning', 'tool_use', 'vision'],
    contextWindow: 256000,
    cost: { inputPerMTokensUsd: 5, outputPerMTokensUsd: 15 },
    latencyHint: 3,
    local: false,
    enabled: false,
  },
  {
    id: 'gpt-4o-mini',
    provider: 'openai',
    displayName: 'GPT-4o mini',
    capabilities: ['chat', 'tool_use', 'vision'],
    contextWindow: 128000,
    cost: { inputPerMTokensUsd: 0.15, outputPerMTokensUsd: 0.6 },
    latencyHint: 1,
    local: false,
    enabled: true,
  },
  {
    id: 'text-embedding-3-small',
    provider: 'openai',
    displayName: 'OpenAI Embedding 3 (small)',
    capabilities: ['embedding'],
    contextWindow: 8192,
    cost: { inputPerMTokensUsd: 0.02, outputPerMTokensUsd: 0 },
    latencyHint: 1,
    local: false,
    enabled: true,
  },
  {
    id: 'claude-sonnet-4',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 4',
    capabilities: ['chat', 'reasoning', 'tool_use', 'vision'],
    contextWindow: 200000,
    cost: { inputPerMTokensUsd: 3, outputPerMTokensUsd: 15 },
    latencyHint: 3,
    local: false,
    enabled: true,
  },
  {
    id: 'gemini-2.5-pro',
    provider: 'google',
    displayName: 'Gemini 2.5 Pro',
    capabilities: ['chat', 'reasoning', 'vision', 'tool_use'],
    contextWindow: 1000000,
    cost: { inputPerMTokensUsd: 1.25, outputPerMTokensUsd: 5 },
    latencyHint: 2,
    local: false,
    enabled: true,
  },
  {
    id: 'deepseek-chat',
    provider: 'deepseek',
    displayName: 'DeepSeek V3',
    capabilities: ['chat', 'reasoning', 'tool_use'],
    contextWindow: 64000,
    cost: { inputPerMTokensUsd: 0.27, outputPerMTokensUsd: 1.1 },
    latencyHint: 2,
    local: false,
    enabled: true,
  },
  {
    id: 'llama3.1',
    provider: 'ollama',
    displayName: 'Llama 3.1 (local)',
    capabilities: ['chat', 'reasoning'],
    contextWindow: 128000,
    cost: { inputPerMTokensUsd: 0, outputPerMTokensUsd: 0 },
    latencyHint: 4,
    local: true,
    enabled: true,
  },
  {
    id: 'nomic-embed-text',
    provider: 'ollama',
    displayName: 'Nomic Embed (local)',
    capabilities: ['embedding'],
    contextWindow: 8192,
    cost: { inputPerMTokensUsd: 0, outputPerMTokensUsd: 0 },
    latencyHint: 2,
    local: true,
    enabled: true,
  },
  {
    id: 'mock-model',
    provider: 'mock',
    displayName: 'Mock Model (offline)',
    capabilities: ['chat', 'reasoning', 'embedding', 'tool_use'],
    contextWindow: 32000,
    cost: { inputPerMTokensUsd: 0, outputPerMTokensUsd: 0 },
    latencyHint: 0,
    local: true,
    enabled: true,
  },
];
